Wip

diff --git a/cli/cli b/cli/cli
--- a/cli/cli
+++ b/cli/cli
@@ -10,43 +10,47 @@ TID_FILE="$CLI_FOLDER/tid"
 TID=${2:-`cat "$TID_FILE"`}
 TASK_FOLDER="$TASKS_FOLDER/$TID"
 
-case "$command" in
-
-help)
-  echo "Команды:
-
-    tasks      - Показать список задач
-    task [N]   - Показать текущую задачу или задачу с номером N
-    goto N     - Перейти к задаче N
-    next       - Перейти к следующей задаче
-    prev, back - Перейти к предыдущей задаче
-    restart    - Начать задание заново
-
-    help       - Показать подсказку"
-;;
-
-tasks)
-  echo "Список заданий"
-;;
-
-task)
-  echo "Текущее задание"
-  cat "$TASK_FOLDER/task"
-;;
-
-goto)
+function check_tid {
   if ! [ -d $TASK_FOLDER ]; then
-    echo "Задача $TID is not found" >&2
-    echo "available tasks are" >&2
-    echo `ls -1 $TASKS_FOLDER` >&2
+    echo "Задача $TID не найдена" >&2
+    echo `$0 tasks` >&2
     exit 1
   fi
 
   if ! [ -d "$CLI_FOLDER/tid" ]; then
     echo 1 > "$CLI_FOLDER/tid"
   fi
+}
 
-  echo "Переход к задаче $TID"
+case "$command" in
+
+help)
+  echo "Команды:
+
+    tasks, list - Показать список задач
+    task [N]    - Показать текущую задачу или задачу с номером N
+    goto N      - Перейти к задаче N
+    next        - Перейти к следующей задаче
+    prev, back  - Перейти к предыдущей задаче
+    restart     - Начать задание заново
+
+    help        - Показать подсказку"
+;;
+
+tasks)
+  echo "Доступные задания: `ls $TASKS_FOLDER | tr "\n" " "`"
+;;
+
+task)
+  check_tid
+  echo "Задача $TID"
+  echo
+  cat "$TASK_FOLDER/task"
+;;
+
+goto)
+  check_tid
+  echo "Пережу к задаче $TID"
 
   echo $TID > "$TID_FILE"
 
@@ -54,7 +58,7 @@ goto)
 ;;
 
 next)
-  echo "Следующая задача"
+  echo "Перехожу к следующей задаче"
 ;;
 
 prev)
@@ -62,7 +66,7 @@ prev)
 ;;
 
 back)
-  echo "Следующая задача"
+  echo "Перехожу к предыдущей задаче"
 ;;
 
 restart)
@@ -79,7 +83,6 @@ esac
 
 exit 0
 
-
 # Инициализация
 
 
@@ -87,37 +90,37 @@ exit 0
 
 # Переключается между уроками
 
-if ! [ -d $task_folder ]; then
-  echo "task is not found" >&2
-  echo "available tasks are" >&2
-  echo `ls -1 $tasks_folder` >&2
-  exit 1
-fi
+# if ! [ -d $task_folder ]; then
+#   echo "task is not found" >&2
+#   echo "available tasks are" >&2
+#   echo `ls -1 $tasks_folder` >&2
+#   exit 1
+# fi
 
-echo "$1" > "$current_folder/tid"
-# cat "$current_folder/tid"
-cat "$task_folder/task"
+# echo "$1" > "$current_folder/tid"
+# # cat "$current_folder/tid"
+# cat "$task_folder/task"
 
-# echo
-# cp -a "$task_folder/." .
+# # echo
+# # cp -a "$task_folder/." .
 
 
 
-# Выводит текущую задачу
+# # Выводит текущую задачу
 
-current_folder=`dirname "$0"`
+# current_folder=`dirname "$0"`
 
-$current_folder/init
+# $current_folder/init
 
-task_id=${1:-`cat "$current_folder/tid"`}
-tasks_folder="$current_folder/../tasks"
-task_folder="$tasks_folder/$task_id"
+# task_id=${1:-`cat "$current_folder/tid"`}
+# tasks_folder="$current_folder/../tasks"
+# task_folder="$tasks_folder/$task_id"
 
-if ! [ -d "$task_folder" ]; then
-  echo "lesson '$task_id' is not found" >&2
-  echo "available lessons are" >&2
-  echo `ls -1 $tasks_folder` >&2
-  exit 1
-fi
+# if ! [ -d "$task_folder" ]; then
+#   echo "lesson '$task_id' is not found" >&2
+#   echo "available lessons are" >&2
+#   echo `ls -1 $tasks_folder` >&2
+#   exit 1
+# fi
 
-cat "$task_folder/task"
+# cat "$task_folder/task"
